# Generated by ChatGPT on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='institution',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
