# Generated by Django 6.0.5 on 2026-05-22 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('no_face', 'No Face Detected'), ('multiple_faces', 'Multiple Faces Detected'), ('face_not_centered', 'Face Not Centered'), ('suspicious_movement', 'Suspicious Movement'), ('tab_switch_detected', 'Tab Switch Detected'), ('exam_terminated', 'Exam Terminated')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='proctoring/')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctor_logs', to='exams.exam')),
            ],
        ),
    ]
