# Generated by Django 6.0.5 on 2026-05-23 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_examprogress'),
        ('proctoring', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proctorlog',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proctorlog',
            name='event_type',
            field=models.CharField(choices=[('no_face', 'No Face Detected'), ('multiple_faces', 'Multiple Faces Detected'), ('face_not_centered', 'Face Not Centered'), ('suspicious_movement', 'Suspicious Movement'), ('tab_switch', 'Tab Switch Detected'), ('fullscreen_exit', 'Fullscreen Exit'), ('copy_attempt', 'Copy Attempt'), ('right_click', 'Right Click'), ('exam_terminated', 'Exam Terminated'), ('suspicious_activity', 'Suspicious Activity')], max_length=50),
        ),
        migrations.CreateModel(
            name='StudentExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('terminated', 'Terminated')], default='ongoing', max_length=20)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_sessions', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'exam')},
            },
        ),
    ]
