# Generated by ChatGPT on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0003_proctorlog_message_alter_proctorlog_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proctorlog',
            name='event_type',
            field=models.CharField(choices=[
                ('no_face', 'No Face Detected'),
                ('multiple_faces', 'Multiple Faces Detected'),
                ('face_not_centered', 'Face Not Centered'),
                ('suspicious_movement', 'Suspicious Movement'),
                ('tab_switch', 'Tab Switch Detected'),
                ('fullscreen_exit', 'Fullscreen Exit'),
                ('copy_attempt', 'Copy Attempt'),
                ('paste_attempt', 'Paste Attempt'),
                ('right_click', 'Right Click'),
                ('exam_started', 'Exam Started'),
                ('exam_submitted', 'Exam Submitted'),
                ('exam_terminated', 'Exam Terminated'),
                ('suspicious_activity', 'Suspicious Activity'),
            ], max_length=50),
        ),
    ]
