# Generated by Django 6.0.5 on 2026-05-26 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsetting',
            options={'verbose_name': 'System Setting', 'verbose_name_plural': 'System Settings'},
        ),
    ]
