# Generated by GitHub Copilot on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_add_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='max_questions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'MCQ'), ('description', 'Description'), ('image', 'Image')], default='mcq', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, to='exams.choice'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='answer_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='is_correct',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
