# Generated by GitHub Copilot on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_question_types_and_exam_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='is_in_bank',
            field=models.BooleanField(default=False),
        ),
    ]
