/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentRouteImport } from './routes/student'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as TeacherStudentsRouteImport } from './routes/teacher.students'
import { Route as TeacherResultsRouteImport } from './routes/teacher.results'
import { Route as TeacherReportsRouteImport } from './routes/teacher.reports'
import { Route as TeacherQuestionsRouteImport } from './routes/teacher.questions'
import { Route as TeacherMonitoringRouteImport } from './routes/teacher.monitoring'
import { Route as TeacherManageExamsRouteImport } from './routes/teacher.manage-exams'
import { Route as TeacherDashboardRouteImport } from './routes/teacher.dashboard'
import { Route as TeacherCreateExamRouteImport } from './routes/teacher.create-exam'
import { Route as StudentStudyPlannerRouteImport } from './routes/student.study-planner'
import { Route as StudentSettingsRouteImport } from './routes/student.settings'
import { Route as StudentResultsRouteImport } from './routes/student.results'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentOngoingRouteImport } from './routes/student.ongoing'
import { Route as StudentNotificationsRouteImport } from './routes/student.notifications'
import { Route as StudentHelpRouteImport } from './routes/student.help'
import { Route as StudentExamsRouteImport } from './routes/student.exams'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as StudentAiTutorRouteImport } from './routes/student.ai-tutor'
import { Route as StudentAiQuizRouteImport } from './routes/student.ai-quiz'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTeachersRouteImport } from './routes/admin.teachers'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminProctoringRouteImport } from './routes/admin.proctoring'
import { Route as AdminExamsRouteImport } from './routes/admin.exams'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as PublicPricingRouteImport } from './routes/_public.pricing'
import { Route as PublicFeaturesRouteImport } from './routes/_public.features'
import { Route as PublicFaqRouteImport } from './routes/_public.faq'
import { Route as PublicContactRouteImport } from './routes/_public.contact'
import { Route as PublicAboutRouteImport } from './routes/_public.about'
import { Route as StudentExamExamIdRouteImport } from './routes/student.exam.$examId'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const TeacherStudentsRoute = TeacherStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherResultsRoute = TeacherResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherReportsRoute = TeacherReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherQuestionsRoute = TeacherQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherMonitoringRoute = TeacherMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherManageExamsRoute = TeacherManageExamsRouteImport.update({
  id: '/manage-exams',
  path: '/manage-exams',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherDashboardRoute = TeacherDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherCreateExamRoute = TeacherCreateExamRouteImport.update({
  id: '/create-exam',
  path: '/create-exam',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentStudyPlannerRoute = StudentStudyPlannerRouteImport.update({
  id: '/study-planner',
  path: '/study-planner',
  getParentRoute: () => StudentRoute,
} as any)
const StudentSettingsRoute = StudentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudentRoute,
} as any)
const StudentResultsRoute = StudentResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentOngoingRoute = StudentOngoingRouteImport.update({
  id: '/ongoing',
  path: '/ongoing',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotificationsRoute = StudentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StudentRoute,
} as any)
const StudentHelpRoute = StudentHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => StudentRoute,
} as any)
const StudentExamsRoute = StudentExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAiTutorRoute = StudentAiTutorRouteImport.update({
  id: '/ai-tutor',
  path: '/ai-tutor',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAiQuizRoute = StudentAiQuizRouteImport.update({
  id: '/ai-quiz',
  path: '/ai-quiz',
  getParentRoute: () => StudentRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProctoringRoute = AdminProctoringRouteImport.update({
  id: '/proctoring',
  path: '/proctoring',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExamsRoute = AdminExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const PublicPricingRoute = PublicPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFeaturesRoute = PublicFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFaqRoute = PublicFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const StudentExamExamIdRoute = StudentExamExamIdRouteImport.update({
  id: '/exam/$examId',
  path: '/exam/$examId',
  getParentRoute: () => StudentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/faq': typeof PublicFaqRoute
  '/features': typeof PublicFeaturesRoute
  '/pricing': typeof PublicPricingRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/proctoring': typeof AdminProctoringRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/ai-quiz': typeof StudentAiQuizRoute
  '/student/ai-tutor': typeof StudentAiTutorRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/exams': typeof StudentExamsRoute
  '/student/help': typeof StudentHelpRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/ongoing': typeof StudentOngoingRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/results': typeof StudentResultsRoute
  '/student/settings': typeof StudentSettingsRoute
  '/student/study-planner': typeof StudentStudyPlannerRoute
  '/teacher/create-exam': typeof TeacherCreateExamRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/manage-exams': typeof TeacherManageExamsRoute
  '/teacher/monitoring': typeof TeacherMonitoringRoute
  '/teacher/questions': typeof TeacherQuestionsRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/results': typeof TeacherResultsRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/student/exam/$examId': typeof StudentExamExamIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/faq': typeof PublicFaqRoute
  '/features': typeof PublicFeaturesRoute
  '/pricing': typeof PublicPricingRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/proctoring': typeof AdminProctoringRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/ai-quiz': typeof StudentAiQuizRoute
  '/student/ai-tutor': typeof StudentAiTutorRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/exams': typeof StudentExamsRoute
  '/student/help': typeof StudentHelpRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/ongoing': typeof StudentOngoingRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/results': typeof StudentResultsRoute
  '/student/settings': typeof StudentSettingsRoute
  '/student/study-planner': typeof StudentStudyPlannerRoute
  '/teacher/create-exam': typeof TeacherCreateExamRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/manage-exams': typeof TeacherManageExamsRoute
  '/teacher/monitoring': typeof TeacherMonitoringRoute
  '/teacher/questions': typeof TeacherQuestionsRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/results': typeof TeacherResultsRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/student/exam/$examId': typeof StudentExamExamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/faq': typeof PublicFaqRoute
  '/_public/features': typeof PublicFeaturesRoute
  '/_public/pricing': typeof PublicPricingRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/proctoring': typeof AdminProctoringRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/ai-quiz': typeof StudentAiQuizRoute
  '/student/ai-tutor': typeof StudentAiTutorRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/exams': typeof StudentExamsRoute
  '/student/help': typeof StudentHelpRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/ongoing': typeof StudentOngoingRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/results': typeof StudentResultsRoute
  '/student/settings': typeof StudentSettingsRoute
  '/student/study-planner': typeof StudentStudyPlannerRoute
  '/teacher/create-exam': typeof TeacherCreateExamRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/manage-exams': typeof TeacherManageExamsRoute
  '/teacher/monitoring': typeof TeacherMonitoringRoute
  '/teacher/questions': typeof TeacherQuestionsRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/results': typeof TeacherResultsRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/student/exam/$examId': typeof StudentExamExamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/student'
    | '/teacher'
    | '/about'
    | '/contact'
    | '/faq'
    | '/features'
    | '/pricing'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/exams'
    | '/admin/proctoring'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/teachers'
    | '/admin/users'
    | '/student/ai-quiz'
    | '/student/ai-tutor'
    | '/student/dashboard'
    | '/student/exams'
    | '/student/help'
    | '/student/notifications'
    | '/student/ongoing'
    | '/student/profile'
    | '/student/results'
    | '/student/settings'
    | '/student/study-planner'
    | '/teacher/create-exam'
    | '/teacher/dashboard'
    | '/teacher/manage-exams'
    | '/teacher/monitoring'
    | '/teacher/questions'
    | '/teacher/reports'
    | '/teacher/results'
    | '/teacher/students'
    | '/admin/'
    | '/student/'
    | '/teacher/'
    | '/student/exam/$examId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/about'
    | '/contact'
    | '/faq'
    | '/features'
    | '/pricing'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/exams'
    | '/admin/proctoring'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/teachers'
    | '/admin/users'
    | '/student/ai-quiz'
    | '/student/ai-tutor'
    | '/student/dashboard'
    | '/student/exams'
    | '/student/help'
    | '/student/notifications'
    | '/student/ongoing'
    | '/student/profile'
    | '/student/results'
    | '/student/settings'
    | '/student/study-planner'
    | '/teacher/create-exam'
    | '/teacher/dashboard'
    | '/teacher/manage-exams'
    | '/teacher/monitoring'
    | '/teacher/questions'
    | '/teacher/reports'
    | '/teacher/results'
    | '/teacher/students'
    | '/'
    | '/admin'
    | '/student'
    | '/teacher'
    | '/student/exam/$examId'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/login'
    | '/register'
    | '/student'
    | '/teacher'
    | '/_public/about'
    | '/_public/contact'
    | '/_public/faq'
    | '/_public/features'
    | '/_public/pricing'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/exams'
    | '/admin/proctoring'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/teachers'
    | '/admin/users'
    | '/student/ai-quiz'
    | '/student/ai-tutor'
    | '/student/dashboard'
    | '/student/exams'
    | '/student/help'
    | '/student/notifications'
    | '/student/ongoing'
    | '/student/profile'
    | '/student/results'
    | '/student/settings'
    | '/student/study-planner'
    | '/teacher/create-exam'
    | '/teacher/dashboard'
    | '/teacher/manage-exams'
    | '/teacher/monitoring'
    | '/teacher/questions'
    | '/teacher/reports'
    | '/teacher/results'
    | '/teacher/students'
    | '/_public/'
    | '/admin/'
    | '/student/'
    | '/teacher/'
    | '/student/exam/$examId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/teacher/students': {
      id: '/teacher/students'
      path: '/students'
      fullPath: '/teacher/students'
      preLoaderRoute: typeof TeacherStudentsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/results': {
      id: '/teacher/results'
      path: '/results'
      fullPath: '/teacher/results'
      preLoaderRoute: typeof TeacherResultsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/reports': {
      id: '/teacher/reports'
      path: '/reports'
      fullPath: '/teacher/reports'
      preLoaderRoute: typeof TeacherReportsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/questions': {
      id: '/teacher/questions'
      path: '/questions'
      fullPath: '/teacher/questions'
      preLoaderRoute: typeof TeacherQuestionsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/monitoring': {
      id: '/teacher/monitoring'
      path: '/monitoring'
      fullPath: '/teacher/monitoring'
      preLoaderRoute: typeof TeacherMonitoringRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/manage-exams': {
      id: '/teacher/manage-exams'
      path: '/manage-exams'
      fullPath: '/teacher/manage-exams'
      preLoaderRoute: typeof TeacherManageExamsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/dashboard': {
      id: '/teacher/dashboard'
      path: '/dashboard'
      fullPath: '/teacher/dashboard'
      preLoaderRoute: typeof TeacherDashboardRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/create-exam': {
      id: '/teacher/create-exam'
      path: '/create-exam'
      fullPath: '/teacher/create-exam'
      preLoaderRoute: typeof TeacherCreateExamRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/study-planner': {
      id: '/student/study-planner'
      path: '/study-planner'
      fullPath: '/student/study-planner'
      preLoaderRoute: typeof StudentStudyPlannerRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/settings': {
      id: '/student/settings'
      path: '/settings'
      fullPath: '/student/settings'
      preLoaderRoute: typeof StudentSettingsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/results': {
      id: '/student/results'
      path: '/results'
      fullPath: '/student/results'
      preLoaderRoute: typeof StudentResultsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/ongoing': {
      id: '/student/ongoing'
      path: '/ongoing'
      fullPath: '/student/ongoing'
      preLoaderRoute: typeof StudentOngoingRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notifications': {
      id: '/student/notifications'
      path: '/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof StudentNotificationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/help': {
      id: '/student/help'
      path: '/help'
      fullPath: '/student/help'
      preLoaderRoute: typeof StudentHelpRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/exams': {
      id: '/student/exams'
      path: '/exams'
      fullPath: '/student/exams'
      preLoaderRoute: typeof StudentExamsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/ai-tutor': {
      id: '/student/ai-tutor'
      path: '/ai-tutor'
      fullPath: '/student/ai-tutor'
      preLoaderRoute: typeof StudentAiTutorRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/ai-quiz': {
      id: '/student/ai-quiz'
      path: '/ai-quiz'
      fullPath: '/student/ai-quiz'
      preLoaderRoute: typeof StudentAiQuizRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/proctoring': {
      id: '/admin/proctoring'
      path: '/proctoring'
      fullPath: '/admin/proctoring'
      preLoaderRoute: typeof AdminProctoringRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exams': {
      id: '/admin/exams'
      path: '/exams'
      fullPath: '/admin/exams'
      preLoaderRoute: typeof AdminExamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/pricing': {
      id: '/_public/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PublicPricingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/features': {
      id: '/_public/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof PublicFeaturesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/faq': {
      id: '/_public/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof PublicFaqRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/student/exam/$examId': {
      id: '/student/exam/$examId'
      path: '/exam/$examId'
      fullPath: '/student/exam/$examId'
      preLoaderRoute: typeof StudentExamExamIdRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicFaqRoute: typeof PublicFaqRoute
  PublicFeaturesRoute: typeof PublicFeaturesRoute
  PublicPricingRoute: typeof PublicPricingRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicContactRoute: PublicContactRoute,
  PublicFaqRoute: PublicFaqRoute,
  PublicFeaturesRoute: PublicFeaturesRoute,
  PublicPricingRoute: PublicPricingRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminExamsRoute: typeof AdminExamsRoute
  AdminProctoringRoute: typeof AdminProctoringRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTeachersRoute: typeof AdminTeachersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminExamsRoute: AdminExamsRoute,
  AdminProctoringRoute: AdminProctoringRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTeachersRoute: AdminTeachersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentAiQuizRoute: typeof StudentAiQuizRoute
  StudentAiTutorRoute: typeof StudentAiTutorRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentExamsRoute: typeof StudentExamsRoute
  StudentHelpRoute: typeof StudentHelpRoute
  StudentNotificationsRoute: typeof StudentNotificationsRoute
  StudentOngoingRoute: typeof StudentOngoingRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentResultsRoute: typeof StudentResultsRoute
  StudentSettingsRoute: typeof StudentSettingsRoute
  StudentStudyPlannerRoute: typeof StudentStudyPlannerRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentExamExamIdRoute: typeof StudentExamExamIdRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAiQuizRoute: StudentAiQuizRoute,
  StudentAiTutorRoute: StudentAiTutorRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentExamsRoute: StudentExamsRoute,
  StudentHelpRoute: StudentHelpRoute,
  StudentNotificationsRoute: StudentNotificationsRoute,
  StudentOngoingRoute: StudentOngoingRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentResultsRoute: StudentResultsRoute,
  StudentSettingsRoute: StudentSettingsRoute,
  StudentStudyPlannerRoute: StudentStudyPlannerRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentExamExamIdRoute: StudentExamExamIdRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherCreateExamRoute: typeof TeacherCreateExamRoute
  TeacherDashboardRoute: typeof TeacherDashboardRoute
  TeacherManageExamsRoute: typeof TeacherManageExamsRoute
  TeacherMonitoringRoute: typeof TeacherMonitoringRoute
  TeacherQuestionsRoute: typeof TeacherQuestionsRoute
  TeacherReportsRoute: typeof TeacherReportsRoute
  TeacherResultsRoute: typeof TeacherResultsRoute
  TeacherStudentsRoute: typeof TeacherStudentsRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherCreateExamRoute: TeacherCreateExamRoute,
  TeacherDashboardRoute: TeacherDashboardRoute,
  TeacherManageExamsRoute: TeacherManageExamsRoute,
  TeacherMonitoringRoute: TeacherMonitoringRoute,
  TeacherQuestionsRoute: TeacherQuestionsRoute,
  TeacherReportsRoute: TeacherReportsRoute,
  TeacherResultsRoute: TeacherResultsRoute,
  TeacherStudentsRoute: TeacherStudentsRoute,
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
