from django.urls import include, path

from api.views import (
    AdminActivityAPIView,
    AdminProctoringAPIView,
    AdminReportsAPIView,
    AdminResultsAPIView,
    AdminSecurityAlertsAPIView,
    AdminSummaryAPIView,
    AdminUsersAPIView,
    StudentDashboardAPIView,
    StudentNotificationsAPIView,
    TeacherAnalyticsAPIView,
    TeacherExamsAPIView,
    TeacherReportsAPIView,
    TeacherResultsAPIView,
    TeacherMonitorAPIView,
    TeacherSummaryAPIView,
    SaveExamProgressAPIView,
)

urlpatterns = [
    path('', include('users.urls')),
    path('', include('exams.urls')),
    path('', include('results.urls')),
    path('', include('proctoring.urls')),
    path('dashboard/student/', StudentDashboardAPIView.as_view(), name='dashboard-student'),
    path('notifications/', StudentNotificationsAPIView.as_view(), name='notifications-student'),
    path('admin/summary/', AdminSummaryAPIView.as_view(), name='admin-summary'),
    path('admin/security-alerts/', AdminSecurityAlertsAPIView.as_view(), name='admin-security-alerts'),
    path('admin/activity/', AdminActivityAPIView.as_view(), name='admin-activity'),
    path('admin/users/', AdminUsersAPIView.as_view(), name='admin-users'),
    path('admin/results/', AdminResultsAPIView.as_view(), name='admin-results'),
    path('admin/proctoring/', AdminProctoringAPIView.as_view(), name='admin-proctoring'),
    path('admin/reports/', AdminReportsAPIView.as_view(), name='admin-reports'),
    path('teacher/summary/', TeacherSummaryAPIView.as_view(), name='teacher-summary'),
    path('teacher/monitor/', TeacherMonitorAPIView.as_view(), name='teacher-monitor'),
    path('teacher/analytics/', TeacherAnalyticsAPIView.as_view(), name='teacher-analytics'),
    path('teacher/exams/', TeacherExamsAPIView.as_view(), name='teacher-exams'),
    path('teacher/results/', TeacherResultsAPIView.as_view(), name='teacher-results'),
    path('teacher/reports/', TeacherReportsAPIView.as_view(), name='teacher-reports'),
    path('exam/save/', SaveExamProgressAPIView.as_view(), name='exam-save'),
    path('exam/progress/', SaveExamProgressAPIView.as_view(), name='exam-progress'),
]
